/**
 * Export Utilities - Convert elements to various formats
 * Supports PDF, PNG, SVG, and ZPL
 */

import { ZPLElement, ExportOptions, PDFExportOptions, LabelConfig } from '@/lib/zpl/types';

/**
 * Export to PDF
 */
export async function exportToPDF(
  elements: ZPLElement[],
  labelConfig: LabelConfig,
  options: PDFExportOptions
): Promise<Blob> {
  try {
    // Dynamic import to avoid loading jsPDF if not needed
    const { jsPDF } = await import('jspdf');
    const { renderElementsToCanvas } = await import('./canvas');

    // Render elements to canvas
    const canvas = await renderElementsToCanvas(elements, labelConfig, {
      dpi: options.dpi,
      quality: options.quality,
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: labelConfig.width > labelConfig.height ? 'landscape' : 'portrait',
      unit: 'mm',
      format: [labelConfig.width, labelConfig.height],
    });

    // Add canvas to PDF
    const imgData = canvas.toDataURL('image/png');
    pdf.addImage(imgData, 'PNG', 0, 0, labelConfig.width, labelConfig.height);

    // Add metadata if requested
    if (options.includeMetadata) {
      pdf.setProperties({
        title: 'Thermal Label',
        subject: 'Generated by Labery ZPL Editor',
        author: 'Labery',
        keywords: 'ZPL, thermal, label',
      });
    }

    return pdf.output('blob');
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to export to PDF');
  }
}

/**
 * Export to PNG
 */
export async function exportToPNG(
  elements: ZPLElement[],
  labelConfig: LabelConfig,
  options: ExportOptions
): Promise<Blob> {
  try {
    const { renderElementsToCanvas } = await import('./canvas');

    // Render elements to canvas
    const canvas = await renderElementsToCanvas(elements, labelConfig, {
      dpi: options.dpi,
      quality: options.quality,
    });

    return new Promise((resolve, reject) => {
      canvas.toBlob(
        (blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Failed to create PNG blob'));
          }
        },
        'image/png',
        options.quality / 100
      );
    });
  } catch (error) {
    console.error('PNG export failed:', error);
    throw new Error('Failed to export to PNG');
  }
}

/**
 * Export to SVG
 */
export async function exportToSVG(
  elements: ZPLElement[],
  labelConfig: LabelConfig,
  _options: ExportOptions
): Promise<Blob> {
  try {
    const { renderElementsToSVG } = await import('./svg');

    // Render elements to SVG
    const svgString = renderElementsToSVG(elements, labelConfig);

    return new Blob([svgString], { type: 'image/svg+xml' });
  } catch (error) {
    console.error('SVG export failed:', error);
    throw new Error('Failed to export to SVG');
  }
}

/**
 * Export to ZPL
 */
export async function exportToZPL(
  elements: ZPLElement[],
  labelConfig: LabelConfig,
  _options: ExportOptions
): Promise<Blob> {
  try {
    const { generateZPLCode } = await import('./zpl');

    // Generate ZPL code
    const zplCode = generateZPLCode(elements, labelConfig);

    return new Blob([zplCode], { type: 'text/plain' });
  } catch (error) {
    console.error('ZPL export failed:', error);
    throw new Error('Failed to export to ZPL');
  }
}

/**
 * Export with automatic format detection
 */
export async function exportLabel(
  elements: ZPLElement[],
  labelConfig: LabelConfig,
  options: ExportOptions
): Promise<Blob> {
  switch (options.format) {
    case 'pdf':
      return exportToPDF(elements, labelConfig, options as PDFExportOptions);
    case 'png':
      return exportToPNG(elements, labelConfig, options);
    case 'svg':
      return exportToSVG(elements, labelConfig, options);
    case 'zpl':
      return exportToZPL(elements, labelConfig, options);
    default:
      throw new Error(`Unsupported export format: ${options.format}`);
  }
}

/**
 * Download exported file
 */
export function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Get file extension for format
 */
export function getFileExtension(format: string): string {
  const extensions: Record<string, string> = {
    pdf: 'pdf',
    png: 'png',
    svg: 'svg',
    zpl: 'zpl',
  };
  return extensions[format] || format;
}

/**
 * Get MIME type for format
 */
export function getMimeType(format: string): string {
  const mimeTypes: Record<string, string> = {
    pdf: 'application/pdf',
    png: 'image/png',
    svg: 'image/svg+xml',
    zpl: 'text/plain',
  };
  return mimeTypes[format] || 'application/octet-stream';
}
